# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
  
    # Install node_modules
    - name: ⬇️ INSTALL DEPENDENCIES (npm)
      run: npm install

    # Run jest tests
    - name: 🧪 RUN TEST (npm)
      run: npm run test

    # Run jest tests
    - name: 🧱 RUN BUILD (npm)
      run: npm run build-turbo

    - name: ⬇️ INSTALL Vercel CLI
      run: npm install --global vercel@latest

    - name: ⬇️ PULL Vercel ENVIRONMENT INFORMATION (vercel)
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

    - name: 🧱 BUILD PROJECT ARTIFACTS (vercel)
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

    - name: ✅ DEPLOY PROJECT ARTIFACTS TO Vercel (vercel)
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
